import {ReactNode} from 'react';
import Header from "@/shared/components/shared/header";
import {Container} from "@/shared/components/shared/container";

export const metadata = {
    title: 'Pizza | Корзина',
    description: 'Generated by Next.js',
}

export default function CheckoutLayout({
                                            children,
                                        }: {
    children: ReactNode
}) {
    return (
        <main className='min-h-screen bg-[#F4F1EE]'>
           <Container>
               <Header hasSearch={false} hasCart={false} className='border-b-gray-200'/>
               {children}
           </Container>
        </main>
    )
}
